CREATE TABLE `submissions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `problem_id` bigint NOT NULL COMMENT '题目ID',
  `contest_id` bigint DEFAULT NULL COMMENT '比赛ID',
  `language` varchar(20) NOT NULL COMMENT '编程语言',
  `code` longtext NOT NULL COMMENT '源代码',
  `status` enum('pending','judging','accepted','wrong_answer','time_limit_exceeded','memory_limit_exceeded','runtime_error','compile_error','presentation_error','output_limit_exceeded','system_error','cancelled') DEFAULT 'pending' COMMENT '判题状态',
  `result` json DEFAULT NULL COMMENT '判题结果JSON',
  `compile_info` json DEFAULT NULL COMMENT '编译信息JSON', 
  `score` int DEFAULT '0' COMMENT '得分',
  `time_used` int DEFAULT '0' COMMENT '运行时间(毫秒)',
  `memory_used` int DEFAULT '0' COMMENT '内存使用(KB)',
  `code_length` int DEFAULT '0' COMMENT '代码长度',
  `is_shared` tinyint(1) DEFAULT '0' COMMENT '是否公开分享',
  `ip_address` varchar(45) DEFAULT NULL COMMENT '提交IP地址',
  `user_agent` varchar(500) DEFAULT NULL COMMENT '用户代理',
  `error_message` text COMMENT '错误信息',
  `judged_at` timestamp NULL DEFAULT NULL COMMENT '判题完成时间',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_problem_id` (`problem_id`),
  KEY `idx_contest_id` (`contest_id`),
  KEY `idx_status` (`status`),
  KEY `idx_language` (`language`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_user_problem` (`user_id`,`problem_id`),
  KEY `idx_contest_user` (`contest_id`,`user_id`),
  KEY `idx_judged_at` (`judged_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='代码提交记录表';

